<a href="https://colab.research.google.com/github/tunahanyalcin/Randomstufff/blob/master/babip_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [96]:
import pandas as pd
import numpy as np
import time
from google.colab import files
uploaded = files.upload() #This row is for uploading the excel file to colab, if you use smtg else, you might not need it
A = np.zeros((73,5))

''' matrix A:
1st column: Counts the number of nan values
2nd column: Counts the number of positive values
3rd column: Aggregation of the positive values
4th column: Counts the number of negative values
5th column: Aggregation of the negative values

Each row represents a participant
'''

dataset = pd.read_excel('babip_test_2.xlsx')        #Reading the file
dataset_2 = dataset.reset_index()                   #Indexing the rows
#print(dataset_2.head())                            #This prints out the first 5 rows of the data

for i in range(73):
  dataset_3 = dataset_2.loc[i, :]                   #This selects one row(i) and all the columns for each loop  
  for j in dataset_3:                               #Columns are defined as 'j'
    if j > 0:
      A[i][1] += 1                                  #A[x][y] selects xth row and yth column of a matrix
      A[i][2] += j
    elif j < 0:
      A[i][3] += 1
      A[i][4] += j
    else:
      A[i][0] += 1

ans =input('What is 21x20?')
if ans == 420:
  print('You smart thang')
else:
  print('Time for more kindergarten :(')
time.sleep(2)
print('Welcome! You will see your result in 10secs...')
time.sleep(3)
print('Waiting for it just makes it better...')
time.sleep(3)
print('I know I know. Just a little more...')
time.sleep(1)
print('3')
time.sleep(1)
print('2')
time.sleep(1)
print('1')
time.sleep(1)

print(A)

print('Thanks for choosing us!')

What is 21x20?3
Time for more kindergarten :(
Welcome! You will see your result in 10secs...
Waiting for it just makes it better...
I know I know. Just a little more...
3
2
1
[[ 42.   5.   8.   2.  -2.]
 [ 47.   1.   1.   1.  -1.]
 [ 42.   2.   5.   5. -10.]
 [ 41.   8.  19.   0.   0.]
 [ 41.   5.  15.   3.  -6.]
 [ 41.   7.  15.   1.  -2.]
 [ 36.   5.  17.   8. -15.]
 [ 37.   4.  15.   8. -12.]
 [ 37.   6.  17.   6. -17.]
 [ 42.   7.  23.   0.   0.]
 [ 45.   1.  10.   3.  -5.]
 [ 42.   6.  19.   1.  -1.]
 [ 42.   5.  22.   2.  -2.]
 [ 42.   1.  13.   6. -12.]
 [ 34.   6.  22.   9. -15.]
 [ 41.   3.  20.   5. -10.]
 [ 48.   1.  16.   0.   0.]
 [ 37.   4.  24.   8. -21.]
 [ 44.   3.  24.   2.  -2.]
 [ 45.   2.  21.   2.  -6.]
 [ 47.   1.  20.   1.  -2.]
 [ 43.   6.  35.   0.   0.]
 [ 45.   1.  22.   3.  -5.]
 [ 46.   2.  25.   1.  -3.]
 [ 40.   7.  39.   2.  -5.]
 [ 46.   2.  28.   1.  -1.]
 [ 45.   3.  31.   1.  -3.]
 [ 48.   1.  27.   0.   0.]
 [ 45.   3.  33.   1.  -2.]
 [ 40.   8.  